#!/bin/bash --login

#PBS -N testing_HJCFIT
#PBS -l select=1
#PBS -l walltime=0:5:0
#PBS -A $BUDGET

# This shifts to the directory that you submitted the job from
cd $WORK
module load anaconda-compute/2.2.0-python2
export CONDA_ENVS_PATH=$WORK/.conda/envs
source activate dcprogs
export PYTHONUSERBASE=$CONDA_ENV_PATH

aprun -n 1 $WORK/HJCFIT/build/likelihood/test_qmatrix
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_idealG
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_idealG_exponentials
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_idealG_laplacian
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_occupancies
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_time_filter
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_laplace_survivor
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_determinant_equation
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_recursion
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_exact_survivor
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_root_finder_intervals
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_root_finder_lower_bound
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_asymptotes
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_brentq
aprun -n 1 $WORK/HJCFIT/build/likelihood/test_likelihood
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_approx_survivor
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_missedeventsG
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_qmatrix
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_log10
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_roots
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_exact_survivor
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_occupancies
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_determinanteq
aprun -n 1 $WORK/HJCFIT/build/documentation/doc_cxx_idealG
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/qmatrix.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/determinant_equation.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/find_roots.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/asymptotes.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/idealg.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/missed_eventsG.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/approx_survivor.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/reduce_likelihood.feature
aprun -n 1 behave $WORK/HJCFIT/likelihood/python/features/time_filter.feature
aprun -n 1 behave $WORK/HJCFIT/documentation/code/exact_survivorpy
aprun -n 1 behave $WORK/HJCFIT/documentation/code/occupancies.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/determinanteq.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/approx_survivor.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/missedeventsG.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/idealG.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/roots.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/log10.py
aprun -n 1 behave $WORK/HJCFIT/documentation/code/qmatrix.py

source deactivate 
